apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: rds!db-e00717ab-9aa9-4012-b08c-af82a3c60bb1