apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: petclinic-db-secret-provider
  namespace: petclinic
spec:
  provider: aws
  secretObjects:
    - secretName: petclinic-db-secret
      type: Opaque
      data:
        - key: postgres_password
          objectName: db_password
        - key: postgres_user
          objectName: db_username
        - key: postgres_url
          objectName: db_url
  parameters:
    objects: |
      - objectName: "rds!db-e00717ab-9aa9-4012-b08c-af82a3c60bb1"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "db_password"
          - path: "username"
            objectAlias: "db_username"
          - path: "'jdbc:postgresql://petclinic-db.cluster-xyz.us-east-1.rds.amazonaws.com:5432/petclinic'"
            objectAlias: "db_url"