apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  {{- if .Values.service.metricsPort }}
  - name: jmx-metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: {{ .Values.service.metricsPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Release.Name }}-app