name: Pipeline
on:
  push:
  # pull_request #
jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Checkstyle
        run: mvn -B checkstyle:checkstyle
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: "target/reports/checkstyle.html"
    
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run tests
        run: mvn test